# Generated by Django 5.1 on 2024-08-12 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.TextField(max_length=255)),
                ('idade', models.IntegerField()),
                ('sexo', models.TextField(max_length=255)),
                ('atividade', models.TextField(max_length=255)),
                ('altura', models.IntegerField()),
                ('peso', models.IntegerField()),
                ('objetivo', models.TextField(max_length=255)),
            ],
        ),
    ]
