# Generated by Django 5.1 on 2024-08-12 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Usuarios',
            new_name='Usuario',
        ),
    ]
