# Generated by Django 5.1 on 2024-08-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0002_rename_usuarios_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tmb',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
