# Generated by Django 5.1 on 2024-08-12 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0003_usuario_tmb'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='imc',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='imc_stat',
            field=models.TextField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
