# Generated by Django 5.1 on 2024-08-14 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0004_usuario_imc_usuario_imc_stat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='atividade',
            field=models.CharField(choices=[('alto', 'Alto'), ('medio', 'Médio'), ('baixo', 'Baixo')], max_length=5),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='objetivo',
            field=models.CharField(choices=[('ganho', 'Ganho'), ('manter', 'Manter'), ('perda', 'Perda')], max_length=6),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='sexo',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1),
        ),
    ]
