# Generated by Django 5.1 on 2024-11-24 21:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0007_cardapio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardapio',
            name='alimentos',
        ),
        migrations.RemoveField(
            model_name='cardapio',
            name='data_criacao',
        ),
        migrations.AddField(
            model_name='cardapio',
            name='alimento',
            field=models.ForeignKey(default='placeholder', on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='app_nutrimax.alimentos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cardapio',
            name='quantidade',
            field=models.FloatField(default=100, help_text='Quantidade em gramas'),
        ),
        migrations.AlterField(
            model_name='cardapio',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='app_nutrimax.usuario'),
        ),
    ]
