# Generated by Django 5.1 on 2024-11-24 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0010_cardapio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cardapio',
        ),
    ]
