# Generated by Django 5.1 on 2024-11-24 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0012_alimentos_novo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alimentos_Novo',
        ),
    ]
