# Generated by Django 5.1 on 2024-11-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0014_alimentosadri'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AlimentosAdri',
        ),
    ]
