# Generated by Django 5.1 on 2024-11-24 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_nutrimax', '0015_delete_alimentosadri'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cardapio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.FloatField(default=100, help_text='Quantidade em gramas')),
                ('alimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='app_nutrimax.alimentos')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardapios', to='app_nutrimax.usuario')),
            ],
        ),
    ]
